#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0

#define ARGUMENTS_PASSED_INCORRECTLY 1

#define FILE_DOES_NOT_EXIST 2
#define COULD_NOT_CLOSE_FILE 3

#define MEMORY_ALIGNMENT_ERROR 4

#define FAILED_TO_READ_ARRAY_ELEM 5

#define LIST_IS_EMPTY 6

#define ELEMENTS_ARE_DIFFERENT 7
#define LISTS_ARE_DIFFERENT 8

#endif
