#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0

#define ARGUMENTS_PASSED_INCORRECTLY 1

#define INCORRECT_PRICE_ENTRY 2

#define FILE_DOES_NOT_EXIST 3
#define COULD_NOT_CLOSE_FILE 4

#define NUMBER_OF_PRODUCTS_UNKNOWN 5
#define IMPOSSIBLE_NUMBER_OF_PRODUCTS 6

#define MEMORY_ALIGNMENT_ERROR 7

#define FAILED_TO_READ_PRODUCT_NAME 13
#define FILE_IS_FULL 11
#define EMPTY_LINE 9
#define FAILED_TO_READ_PRODUCT_PRICE 10
#define FILE_IS_NOT_FULL 12

#endif
