#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0

#define ARGUMENTS_INCORRECTLY_TRANSFERRED 1
#define FILE_OPEN_ERROR 2
#define ERROR_READING_FROM_FILE 3
#define FILE_EMPTY 4
#define ARRAY_FILL_ERROR 5
#define FILE_POINTER_SHIFT_ERROR 6
#define FAILED_TO_CLOSE_FILE 7
#define MEMORY_ALLOCATION_ERROR 8
#define NEW_FILE_EMPTY 9
#define INCORRECT_DATA_FOR_FILTRATION 10

#define DIFFERENT_LENGTH_OF_ARRAYS 1
#define  ERROR_FOUND 2

#endif
