#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0

#define ROW_LENGTH_ERROR 1
#define NEGATIVE_ROW_LENGTH 2
#define COLUMN_LENGTH_ERROR 3
#define NEGATIVE_COLUMNS_LENGTH 4

#define FAILED_TO_ALLOCATE_MEMORY 5
#define MATRIX_READ_ERROR 6

#define POWER_MATRIX_A_ERROR 7
#define NEGATIVE_POWER_MATRIX_A 8
#define POWER_MATRIX_B_ERROR 9
#define NEGATIVE_POWER_MATRIX_B 10

#define DIFFERENT_NUMBER_ROWS 11
#define DIFFERENT_NUMBER_COLUMNS 12
#define COMPARE_ERROR 13

#endif
